<?php

namespace app\controllers;

use app\models\db\Page;
use app\system\base\Controller;
use yii\web\NotFoundHttpException;
use app\system\template\TemplateStore;

class PageController extends Controller
{
    public function beforeAction($action)
    {
        TemplateStore::setVar("CONTAINER.LAYOUT.SITE.CLASS", 'container');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex($slug = null)
    {
        $page = Page::findOne(['slug' => $slug]);
        if ($page) {
            return $this->render('index', ['page' => $page]);
        } else {
            throw new NotFoundHttpException("Страница не найдена");
        }
    }

}
